### ISSUE TITLE
add a dependency after webpack-dev-server already started and serving other assets?

### ISSUE THREAD

**Issue by TSMMark** [tatethurston/webpack-inject-entry-plugin#1]
Hi, is it possible to use this plugin to add a dependency AFTER webpack-dev-server has already started and has already been serving other assets?

e.g. initial build includes entries A, B, C. After some time / some external event, add entry D to the mix to be built too.

Thanks!

**Comment by tatethurston** [comment]
@TSMMark could you expand on this use case more? A few quick questions:

- Why can't D be built immediately? 
- Will D be it's own entry, or added to an existing named chunk / entry? 
- Is the goal to lazy build / build files on demand?
- Can webpack-dev-server be run in watch mode? Curious if a noop file that gets overwritten by some asynchronous process might achieve this for you without any plugin.

**Comment by TSMMark** [comment]
Sure, so WDS in my dev env has several different front ends (entries A, B, C, D), but I usually only work on one at a time. When I'm developing I want the initial WDS build to be as minimal as possible and build as quickly as possible. My WDS setup currently has some gulp wrapper tasks that allow the developer to specify which entrypoints to build, via CLI arguments. 

So I can already spin up WDS to build entry A, B, or C, in any combination, but I have to *start* WDS with this in mind, and if I already have WDS running for one entry A, B, or C, and then decide I actually need D too, I would have to kill WDS and start it over with new CLI args. I would love to find some mechanism to be able to do while WDS is still running and not waste time rebuilding. (We've already got babel caching and webpack caching in place)

It's not exactly the same, but we've been checking out the lazy aspects of Vite as a bundler, and it got us thinking.

If this is not supported but you are able to find any way to do this please let me know, I may be able to create a custom plugin. Thanks for your time

**Comment by tatethurston** [comment]
@TSMMark Got it. webpack-inject-entry-plugin won't be the right primitive here -- it injects into an existing named entry, but you'll want to have entries for A B C and D defined, but lazily built / built on demand. This is a neat idea.

Would you want A, B, C and D to have their own webpack configs? Or all belong to the same webpack config?

For the former, you would probably want to look into something like https://webpack.js.org/concepts/module-federation/. For the later, I see a few open source attempts such as https://github.com/flut1/webpack-on-demand and https://github.com/tfoxy/webpack-lazy-dev-build. NextJS also does something like this with their development server.

I'd start by taking a look at those and if nothing quite works the way you'd expect and you want to collaborate on something let me know.

**Comment by TSMMark** [comment]
Nice finds, but neither look webpack 5 compatible. Will continue digging. Thanks

**Comment by TSMMark** [comment]
> Would you want A, B, C and D to have their own webpack configs? Or all belong to the same webpack config?

they all have 1 config in our setup
